language: ruby
rvm:
- 2.0.0
branches:
  except:
  - CURRENT
notifications:
  irc:
    channels:
    - irc.freenode.net#theodi
    template:
    - '%{repository} %{branch} - %{message} %{build_url}'
    on_success: change
    on_failure: always